package by.aurorasoft.chart.model.chart.format.formatter;

import by.aurorasoft.chart.model.chart.format.formatter.exception.ScreeningChartException;
import org.icepear.echarts.Chart;
import org.icepear.echarts.render.Engine;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.io.File;
import java.io.IOException;

import static java.lang.System.nanoTime;
import static java.lang.Thread.currentThread;
import static java.nio.charset.StandardCharsets.UTF_8;
import static java.util.concurrent.TimeUnit.MILLISECONDS;
import static org.apache.commons.io.FileUtils.delete;
import static org.apache.commons.io.FileUtils.writeStringToFile;
import static org.openqa.selenium.OutputType.BYTES;

/**
 * Formats chart to image's bytes by saving html of this chart in temp file, opening it in browser and screening it.
 * In the end this html file will be removed.
 * Name's of temp files generated by current nanoseconds, because of file's names should be unique for
 * formatting in parallel.
 */
public final class ChartToImageFormatter implements ChartFormatter {
    private static final String TEMPLATE_PATH_NAME_TEMP_FILE = "temp-%d.html";
    private static final long AMOUNT_MILLIS_TO_WAIT_CHART_LOADING = 100;

    @Override
    public byte[] format(Chart<?, ?> chart, Engine engine) {
        return screenChart(chart, engine);
    }

    private static byte[] screenChart(Chart<?, ?> chart, Engine engine) {
        try {
            final File tempFile = writeChartIntoTempFile(chart, engine);
            try {
                return screenChart(tempFile);
            } finally {
                delete(tempFile);
            }
        } catch (final IOException cause) {
            throw new ScreeningChartException(cause);
        }
    }

    private static File writeChartIntoTempFile(Chart<?, ?> chart, Engine engine)
            throws IOException {
        final String chartHtml = engine.renderHtml(chart);
        final File tempFile = createTempFile();
        writeStringToFile(tempFile, chartHtml, UTF_8);
        return tempFile;
    }

    private static File createTempFile() {
        final String pathName = generatePathNameOfTempFile();
        return new File(pathName);
    }

    private static String generatePathNameOfTempFile() {
        return String.format(TEMPLATE_PATH_NAME_TEMP_FILE, nanoTime());
    }

    private static byte[] screenChart(File file) {
        final WebDriver driver = new ChromeDriver();
        try {
            driver.get(file.toURI().toString());
            waitChartLoading();
            return ((TakesScreenshot) driver).getScreenshotAs(BYTES);
        }
        catch (final InterruptedException cause) {
            currentThread().interrupt();
            throw new ScreeningChartException(cause);
        }
        finally {
            driver.quit();
        }
    }

    private static void waitChartLoading()
            throws InterruptedException {
        MILLISECONDS.sleep(AMOUNT_MILLIS_TO_WAIT_CHART_LOADING);
    }
}
